services:
  uptime-xray:
    build:
      context: .
      dockerfile: Dockerfile
    image: uptime-xray:latest
    container_name: uptime-xray
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
